### PR TITLE
Fix the axes of weight for height

### PR DESCRIPTION
**Pull request by bjoshuadevelopment**

### CODE REVIEW

**Comment by bjoshuadevelopment** [comment]
@mseaton cloud you check this out please.

**Comment by mseaton** [comment]
Hi @bjoshuadevelopment .  Sure, without any ticket in JIRA, can you please add some more explanation to the PR description in terms of what this is doing, why it is needed, etc?  Maybe include a before/after screenshot showing what you are intending to achieve?  From a quick look at the PR, it looks like you are swapping the height and weight to different axes in the graph, but why?

**Comment by bjoshuadevelopment** [comment]
Hi @mseaton , according to our pdc clinician, the graphs weight for height and weight for length have y - axis as height / length and x-axis as weight, which mis-informs them.


Yet it is supposed to be weight for y-axis and height/ length for x-axis like this WHO chart

https://cdn.who.int/media/docs/default-source/child-growth/child-growth-standards/indicators/weight-for-length-height/cht-wfh-girls-z-2-5.pdf?sfvrsn=364208a4_9

**Comment by mseaton** [comment]
Thanks @bjoshuadevelopment .  Can you add an "after" screenshot after the changes from this PR are applied?

We also may want to make a major version change of the module since this is a significant change to existing behavior.

**Comment by bjoshuadevelopment** [comment]
Thanks @mseaton,

**Before.**
image


**After**.

image

I don't know what best version numbers to use. maybe from 2.1.1-SNAPSHOT to 2.1.2-SNAPSHOT  or 2.2.1-SNAPSHOT

**Review by mseaton — APPROVED** [review]
Looks good.  I'd recommend bumping the version up to 3.0.0-SNAPSHOT

**Comment by bjoshuadevelopment** [comment]
Thanks @mseaton , I just added pumped version.

**Pull request merged**
